[LOCAL]
spark.app.name = retail-local

[TEST]
spark.app.name = retail-test
spark.exector.instances = 3
spark.exector.cores = 5
spark.exector.memory = 15GB

[PROD]
spark.app.name = retail-prod
spark.exector.instances = 3
spark.exector.cores = 5
spark.exector.memory = 15GB